import { Profile } from './profile';

export const PROFILES: Profile[] = [
    {
        id: 1,
        name: 'Adrià Ortolà',
        born: '20.08.1993',
        birthPlace:	'Groesbeek, Spain',
        nationality: 'Spain',
        height: '187cm',
        weight:	'75 kg',
        position: 'Goalkeeper',
        foot: 'left',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Spain.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'GoalKeeper',	
        jerseyNumber: 13,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '07/2017 - 06/2020',
        image: '/assets/images/13Ortola.jpg'
    },
    {
        id: 2,
        name: 'Jasper Cillessen',
        born: '22.04.1989',
        birthPlace:	'Groesbeek, Netherlands',
        nationality: 'Netherlands',
        height: '185cm',
        weight:	'83 kg',
        position: 'Goalkeeper',
        foot: 'right',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Netherlands.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'GoalKeeper',	
        jerseyNumber: 13,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '07/2017 - 06/2020',
        image: '/assets/images/13Cillessen.jpg'
        
    },
    {
        id: 3,
        name: 'Marc-André ter Stegen',
        born: '30.04.1992',
        birthPlace:	'Mönchengladbach, Germany',
        nationality: 'Germany',
        height: '189cm',
        weight:	'85 kg',
        position: 'Goalkeeper',
        foot: 'right',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Germany.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'GoalKeeper',	
        jerseyNumber: 1,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '07/2017 - 06/2020',
        image: '/assets/images/1Stegan.jpg'
    },
    {
        id: 4,
        name: 'Aleix Vidal',
        born: '21.08.1989',
        birthPlace:	'Valls, Spain',
        nationality: 'Spain',
        height: '177 cm',
        weight:	'70 kg',
        position: 'Right Back, Right Midfielder',
        foot: 'right',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Spain.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'Defender',	
        jerseyNumber: 22,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '07/2015 - 06/2020',
        image: '/assets/images/22Vidal.jpg'
    },
    {
        id: 5,
        name: 'Cucurella',
        born: '22.07.1998',
        birthPlace:	'Alella, Spain',
        nationality: 'Spain',
        height: '172 cm',
        weight:	'68 kg',
        position: 'Left Back',
        foot: 'left',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Spain.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'Defender',	
        jerseyNumber: 36,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '10/2017 - 06/2018',
        image: '/assets/images/36Cucurella.jpg'
    },
    {
        id: 6,
        name: 'David Costas',
        born: '26.03.1995',
        birthPlace:	'Redondela, Spain',
        nationality: 'Spain',
        height: '183 cm',
        weight:	'80 kg',
        position: 'Centre Back, Right Back',
        foot: 'right',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Spain.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'Defender',	
        jerseyNumber: 39,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '11/2017 - 06/2018',
        image: '/assets/images/39Costas.jpg'
    },
    {
        id: 7,
        name: 'André Gomes',
        born: '30.07.1993',
        birthPlace:	'Vila Nova de Gaia, Portugal',
        nationality: 'Portugal',
        height: '188 cm',
        weight:	'84 kg',
        position: 'Central Midfielder, Defensive Midfielder',
        foot: 'right',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Portugal.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'Midfielder',	
        jerseyNumber: 21,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '07/2016 - 06/2021',
        image: '/assets/images/21Gomes.jpg'
    },
    {
        id: 8,
        name: 'Busquets',
        born: '16.07.1988',
        birthPlace:	'Sabadell, Spain',
        nationality: 'Spain',
        height: '189 cm',
        weight:	'76 kg',
        position: 'Defensive Midfielder, Centre Back',
        foot: 'right',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Spain.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'Midfielder',	
        jerseyNumber: 5,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '07/2008 - 06/2021',
        image: '/assets/images/5Busquets.jpg'
    },
    {
        id: 9,
        name: 'Carles Aleñá',
        born: '	05.01.1998',
        birthPlace:	'Mataró, Spain',
        nationality: 'Spain',
        height: '180 cm',
        weight:	'73 kg',
        position: 'Central Midfielder',
        foot: 'left',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Spain.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'Midfielder',	
        jerseyNumber: 26,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '10/2017 - 06/2020',
        image: '/assets/images/26Alena.jpg'
    },
    {
        id: 10,
        name: 'Lionel Messi',
        born: '24.06.1987',
        birthPlace:	'Rosario, Argentina',
        nationality: 'Argentina',
        height: '170 cm',
        weight:	'72 kg',
        position: '	Centre Forward, Right Winger',
        foot: 'left',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Spain.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'Forward',	
        jerseyNumber: 10,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '07/2004 - 06/2021',
        image: '/assets/images/10Messi.jpg'
    },
    {
        id: 11,
        name: 'Ousmane Dembélé',
        born: '15.05.1997',
        birthPlace:	'Vernon, France',
        nationality: 'France',
        height: '178 cm',
        weight:	'67 kg',
        position: 'Left Winger, Right Winger',
        foot: 'both',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Spain.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'Forward',	
        jerseyNumber: 11,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '08/2017 - 06/2022',
        image: '/assets/images/11Dembele.jpg'
    },
    {
        id: 12,
        name: 'Paco Alcácer',
        born: '30.08.1993',
        birthPlace:	'Torrent, Spain',
        nationality: 'Spain',
        height: '175 cm',
        weight:	'71 kg',
        position: 'Centre Forward, Left Winger',
        foot: 'both',
        playingCountry: 'Spain',
        iconCountry: '/assets/images/Spain.gif',
        currentTeam: 'FC Bercelona',
        currentPosition: 'Forward',	
        jerseyNumber: 17,
        iconCurrentCountry: '/assets/images/Spain.gif',
        career: '08/2016 - 06/2021',
        image: '/assets/images/17Alcacer.jpg'
    },
];